name: Gaussian Solver CI

on: [push, pull_request]

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          libeigen3-dev \
          build-essential \
          cmake \
          libgtest-dev \
          googletest
        
    - name: Build and install GTest
      run: |
        cd /usr/src/gtest
        sudo cmake CMakeLists.txt
        sudo make
        sudo cp *.a /usr/lib
        
    - name: Build project
      run: |
        make
        
    - name: Run unit tests
      run: |
        make test
        
    - name: Test sample files
      run: |
        make test-samples
        
    - name: Check formatting
      run: |
        sudo apt-get install -y clang-format
        find src include test -name '*.cpp' -o -name '*.h' | xargs clang-format --dry-run --Werror
