name: ASCII85

on: 
  push:
    branches:
      - main
  pull_request:
    branches:
        - main
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install build tools and Google Test
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential libgtest-dev

          cd /usr/src/googletest && sudo cmake . && sudo make
          sudo cp /usr/src/googletest/lib/*.a /usr/lib

      - name: Build the project
        run: |
          make

      - name: Run tests
        run: |
          ./test_ascii85
      - name: Python
        run: python3 test_random.py

      - name: Clean 
        run: |
          make clean

      
