name: ASCII85 CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential libgtest-dev python3 python3-pip

      - name: Build Google Test Manually
        run: |
          git clone https://github.com/google/googletest.git
          cd googletest
          mkdir build && cd build
          cmake ..
          sudo make install

      - name: Compile Project
        run: make

      - name: Run Tests
        run: ./test_suite  # Исправлено

      - name: Run Python Tests
        run: python3 scripts/test_random.py
