name: ASCII85 CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Установка зависимостей
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential libgtest-dev python3 python3-pip

      - name: Сборка Google Test
        run: |
          git clone https://github.com/google/googletest.git
          cd googletest
          mkdir build && cd build
          cmake .. -DCMAKE_INSTALL_PREFIX=/usr
          sudo make install

      - name: Исправление путей к Google Test
        run: |
          sudo cp -r /usr/lib/googletest/* /usr/lib/
          sudo cp -r /usr/include/googletest/* /usr/include/

      - name: Сборка проекта
        run: |
          make clean
          make

      - name: Запуск тестов
        run: ./test_ascii85  # Используйте правильное имя тестового бинарника

      - name: Запуск Python тестов
        run: python3 scripts/test_random.py
