name: ASCII85 CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential libgtest-dev python3 python3-pip
        sudo pip3 install base64  # Хотя base64 уже встроен, но для тестов

    - name: Build Google Test
      run: |
        cd /usr/src/gtest
        sudo cmake .
        sudo make
        sudo cp *.a /usr/lib

    - name: Compile project
      run: make

    - name: Run C++ tests
      run: ./tests

    - name: Run Python tests
      run: python3 scripts/test_random.py

    - name: Check code style (optional)
      run: |
        # Добавьте проверку стиля (например, clang-format)
        # clang-format --version
        # clang-format -style=file -output-replacements-xml src/*.cpp | grep -q '<replacement ' && (echo 'Style errors found!' && exit 1) || echo 'Style OK'
